#!/bin/bash

echo "Create tmux configuration file (If doesn't exists)"
if [ ! -a ~/.tmux.conf ]; then ln -s $(pwd)/.tmux.conf ~/.tmux.conf > /dev/null 2>&1; fi

echo "Create vimrc file (If doesn't exists)"
if [ ! -a ~/.vimrc ]; then ln -s $(pwd)/.vimrc ~/.vimrc > /dev/null 2>&1; fi

echo "Create vim configuration folder (If doesn't exists)"
if [ ! -d ~/.vim ]; then ln -s $(pwd)/.vim ~/.vim > /dev/null 2>&1; fi

echo "Create zsh configuration file (If doesn't exists)"
if [ ! -a ~/.zshrc ]; then ln -s $(pwd)/.zshrc ~/.zshrc > /dev/null 2>&1; fi
